server {
    listen              443 ssl;
    server_name         eabushak.42.fr;

    ssl_protocols       TLSv1.3 TLSv1.2;
    ssl_certificate     /etc/nginc/ssl/inception.crt;
    ssl_certificate_key /etc/nginc/ssl/inception.key;

    root                /var/www/html
    index               index.html index.php
    location ~ \.php${
        
    }

}