server {
    listen              443 ssl;
    listen              [::]:443 ssl; # does the same thing but for IPv6
    server_name         eabushak.42.fr;

    ssl_protocols       TLSv1.3 TLSv1.2; # Tranport layer security 
    ssl_certificate     /etc/nginc/ssl/inception.crt;
    ssl_certificate_key /etc/nginc/ssl/inception.key;

    root                /var/www/html
    index               index.html index.php
    # every single req handled here by default
    location / {
        # nginx will look at the folder from left to right
        # $uri it check if real file exist if yes > show it
        # $uri/ it check it real folder exist if yes > open it
        # if NGINX cannot finde real files or folder it habd the req for
        # the main WordPress file (index.php)
        # word press whill creat clean human readable website-link
        try_files $uri $uri/ /index.php?$args
    }
    location ~ \.php$ {
        include fastcgi_params;
        ########################
    }
    location ~ \.php${
        
    }
    location ~ /\. {
        deny all;
    }
    # deny upload files that contain .php code
    location ~* /(?:uploads|files)/.*\.php$ {
        deny all;
    }

}