services:
 nginx:
  build:
   context: ./requirements/nginx
   dockerfile: dockerfile
  container_name: nginx
  networks:
   - inception
  ports:
   - "443:443"
  volumes:
   - wordpress_data:/var/www/html/
  depends_on:
    - wordpress
  restart: always

 mariadb:
  build:
   context: ./requirements/mariadb
   dockerfile: dockerfile
  container_name: mariadb
  networks:
    - inception
  volumes:
    - mariadb_data:/var/lib/mysql/
  env_file: .env
  secrets:
    - db_password
    - db_root_password
  environment:
    db_password: /run/secrets/db_password
    db_root_password: /run/secrets/db_root_password
  healthcheck:
    test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    interval: 10s # check the helth every 10s
    timeout: 5s # wait 5s to respone
    retries: 5 # number of tries
    start_period: 30s # if give the database 30 sec to work
  restart: always

 wordpress:
  build:
   context: ./requirements/wordpress
   dockerfile: dockerfile
  container_name: wordpress
  networks:
   - inception
  volumes:
   - wordpress_data:/var/www/html/
  env_file: .env
  secrets:
    - wp_admain_password
    - wp_user_password
  environment:
    wp_user_password: /run/secrets/wp_user_password
    wp_admain_password: /run/secrets/wp_admain_password
  depends_on:
    mariadb:
      condition: service_healthy
  restart: always

networks: # our privet connection between the containers
  inception:
    driver: bridge # this make a vertual switch between the container
                   # and make is isolated from my LAN network
    name: inception

volumes:
 mariadb_data:
  driver: local
  driver_opts:
   type: none
   o: bind
   device: /home/eabushak/data/mariadb
 wordpress_data:
  driver: local
  driver_opts:
   type: none
   o: bind
   device: /home/eabushak/data/wordpress

secrets:
 db_password:
  file: ../secrets/db_password.txt
 db_root_password:
  file: ../secrets/db_root_password.txt
 wp_admain_password:
  file: ../secrets/wp_admain_password.txt
 wp_user_password:
  file: ../secrets/wp_user_password.txt
  





