FROM debian:bookworm

RUN apt-get update && apt install -y mariadb-server \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /var/lib/mysql/*

EXPOSE 3306

COPY conf/script.sh /script.sh
RUN chmod +x script.sh
CMD [ "./script.sh" ]