FROM debian:bookworm

RUN apt-get update && apt install -y mariadb-server \
    && rm -rf /var/lib/apt/lists/*


COPY /conf/script.sh /script.sh

RUN chmod +x /script.sh

CMD ["mariadb", "-g", "daemon off;"]