FROM debian:bookworm

RUN apt-get update && apt-get install -y \
    # php-fpm FastCGI web server protocol
    # for a fast comu between the web server
    # and the app by keeping  app proc alive 
    php-fpm \
    # translator
    php-mysql \
    # command line to interact with maria
    mariadb-client \
    # download files from internet
    wget \
    && rm -rf /var/lib/apt/lists/*

# editing the php config filr to listern on 9000
# that way nginx can forward php req across the net
RUN sed -i 's/listen = \/run\/php\/php8.2-fpm.sock/listen = 9000/g' /etc/php/8.2/fpm/pool.d/www.conf

# Download WP-CLI - The WordPress Command Line Interface
# to managing wordpress throw command line
RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
    && chmod +x wp-cli.phar \
    && mv wp-cli.phar /usr/local/bin/wp

# Create the PID directory for PHP-FPM
RUN mkdir -p /run/php

# 5. Copy the entrypoint
COPY conf/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 9000

# We will run PHP-FPM in the foreground in the entrypoint script, 
# but we set the entrypoint command here.
ENTRYPOINT ["/entrypoint.sh"]