FROM debian:bookworm

RUN apt-get update && apt-get install -y \
    nginx \
    openssl \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /etc/nginx/ssl && \
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/nginx/ssl/inception.key\
    -out /etc/nginx/ssl/inception.crt\
    -subj "/C=JU/ST=IRBID/L=IRBID/o=42irbid/OU=Dep/CN=eabushak.42.fr"

COPY conf/nginx.conf /etc/nginx/conf.d/

EXPOSE 443

# We explicitly tell NGINX NOT to run in the background. 
# It stays attached to the terminal as PID 1. If NGINX crashes, the container crashes (which is what we want for auto-restarts)
CMD ["nginx", "-g", "daemon off;"]